Nursoft/Models/Testimonial.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;

namespace Nursoft.Models
{
    public class Testimonial
    {
        public int Id { get; set; }
        [Required, StringLength(100), DisplayName("Ad")]
        public string Name { get; set; }
        [Required, StringLength(5000), DisplayName("Rəy")]
        public string Description { get; set; }
        [Required, StringLength(100), DisplayName("Vəzifə")]
        public string Position { get; set; }

    }
}

Nursoft/Areas/Admin/Controllers/TestimonialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nursoft.DAL;
using Nursoft.Models;

namespace Nursoft.Areas.Admin.Controllers
{
    [Area("admin")]
    public class TestimonialController : Controller
    {
        private readonly DataContext _context;

        public TestimonialController(DataContext context)
        {
            _context = context;
        }
        // GET: Testimonial
        public async Task<ActionResult> Index()
        {
            var testimonials = await _context.Testimonials.ToListAsync();
            return View(testimonials);
        }


        // GET: Testimonial/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Testimonial/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Testimonial testimonial)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(testimonial);
                }
               await _context.Testimonials.AddAsync(testimonial);
               await _context.SaveChangesAsync();
               TempData["success"] = "Rəy uğurla əlavə edildi";
               return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(testimonial);
            }
        }

        // GET: Testimonial/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testimonial = _context.Testimonials.FirstOrDefault(x => x.Id == id);
            if (testimonial == null)
            {
                return NotFound();
            }
            return View(testimonial);
        }

        // POST: Testimonial/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Testimonial testimonial)
        {
            if (!ModelState.IsValid)
            {
                return View(testimonial);
            }


            var testDb = await _context.Testimonials.FindAsync(testimonial.Id);

            testDb.Name = testimonial.Name;
            testDb.Description = testimonial.Description;
            testDb.Position = testimonial.Position;
            await _context.SaveChangesAsync();
            TempData["warning"] = "Rəy uğurla dəyişdirildi";
            return RedirectToAction(nameof(Index));
        }

        // GET: Testimonial/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testimonial = _context.Testimonials.FirstOrDefault(x => x.Id == id);
            if (testimonial == null)
            {
                return NotFound();
            }
            return View(testimonial);
        }

        // POST: Testimonial/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteTestimonial(int? id)
        {
            try
            {
                // TODO: Add delete logic here
                if (id == null)
                {
                    return NotFound();
                }

                var testimonial = _context.Testimonials.FirstOrDefault(x => x.Id == id);
                if (testimonial == null)
                {
                    return NotFound();
                }
                _context.Testimonials.Remove(testimonial);
                _context.SaveChanges();
                TempData["danger"] = "Rəy uğurla silindi";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Nursoft/Areas/Admin/Views/Testimonial/Create.cshtml
@model Testimonial

@{
    ViewBag.Title = "Yeni rəy";
    Layout = "_Layout";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Yeni rəy
    </h1>
</section>

<!-- Main content -->
<section class="content">

    <form asp-action="Create" asp-controller="Testimonial" enctype="multipart/form-data">
        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Yeni rəyin əlavə edilməsi</h3>
            </div>

            <div style="color: red" asp-validation-summary="All"></div>
            <div class="box-body">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" type="text" class="form-control" placeholder="">
                        <span style="color: red" asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <input asp-for="Description" type="text" class="form-control" placeholder="">
                        <span style="color: red" asp-validation-for="Description"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Position"></label>
                        <input asp-for="Position" type="text" class="form-control" placeholder="">
                        <span style="color: red" asp-validation-for="Position"></span>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <a asp-controller="Testimonial" asp-action="Index" class="btn btn-default">Geriyə qayıt</a>
                <input type="submit" class="btn btn-success pull-right" value="Əlavə et">
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->
    </form>

</section>
<!-- /.content -->

Nursoft/Areas/Admin/Views/Testimonial/Delete.cshtml
@model Testimonial

@{
    ViewBag.Title = "Rəyi sil";
    Layout = "_Layout";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Rəyi sil
    </h1>
</section>

<!-- Main content -->
<section class="content">

    <form asp-action="Delete" asp-controller="Testimonial">
        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Rəyi silməyi əminsiniz?</h3>
            </div>
            <div class="box-body">
                <div class="col-md-6">
                    <div>
                        <h3>@Model.Name</h3>
                        <div>@Model.Description</div>
                        <div>@Model.Position</div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <a asp-action="Index" asp-controller="Testimonial" class="btn btn-default">Geriyə qayıt</a>
                <button type="submit" class="btn btn-warning pull-right">Sil</button>

            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->
    </form>

</section>
<!-- /.content -->

Nursoft/Areas/Admin/Views/Testimonial/Edit.cshtml
@model Testimonial

@{
    ViewBag.Title = "Rəyi dəyişmək";
    Layout = "_Layout";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Rəyi dəyişmək
    </h1>
</section>

<!-- Main content -->
<section class="content">

    <form asp-action="Edit" asp-controller="Testimonial" method="post" enctype="multipart/form-data">
        <!-- Default box -->
        <div class="box">
            <div asp-validation-summary="All" style="color: red"></div>
            <div class="box-body">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input type="text" class="form-control" asp-for="Name" placeholder="">
                        <span style="color: red" asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <input type="text" class="form-control" asp-for="Description" placeholder="">
                        <span style="color: red" asp-validation-for="Description"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Position"></label>
                        <input type="text" class="form-control" asp-for="Position" placeholder="">
                        <span style="color: red" asp-validation-for="Position"></span>
                    </div>


                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <a asp-action="Index" asp-controller="Testimonial" class="btn btn-default">Geriyə qayıt</a>
                <button type="submit" class="btn btn-warning pull-right edit">Dəyiş</button>
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->
    </form>

</section>

Nursoft/Areas/Admin/Views/Testimonial/Index.cshtml
@model IEnumerable<Nursoft.Models.Testimonial>

@{
    Layout = "_Layout";
    ViewBag.Title = "Rəylər";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Xəbərlər
    </h1>
    <ol class="breadcrumb">
        <li><a asp-controller="Home" asp-action="Index"><i class="fa fa-dashboard"></i> Əsas</a></li>
        <li class="active">Rəylər</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="box">
        <!-- /.box-header -->
        <div class="box-body">
            <partial name="_SuccessMessagePartial" />
            <partial name="_DangerMessagePartial" />
            <partial name="_WarningMessagePartial" />
            <div class="form-group">
                <a asp-controller="Testimonial" asp-action="Create" class="btn btn-success">Yeni rəy əlavə et</a>
            </div>
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Ad</th>
                        <th>Rəy</th>
                        <th>Vəzifə</th>
                        <th style="display: none"></th>
                        <th style="display: none"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var testimonial in Model)
                    {
                        <tr>
                            <td>@testimonial.Name</td>
                            <td>@testimonial.Description</td>
                            <td>
                                @testimonial.Position
                            </td>
                            <td>
                                <a asp-action="Edit" asp-controller="Testimonial" asp-route-id="@testimonial.Id" class="fa fa-pencil"></a>
                                <a asp-action="Delete" asp-controller="Testimonial" asp-route-id="@testimonial.Id" class="fa fa-remove"></a>
                            </td>
                            <td style="display: none"></td>
                            <td style="display: none"></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->

</section>
<!-- /.content -->